version: '3.6'
services:
  redis:
    image: "redis:alpine"
    hostname: redis_test

  app_test:
    build: .
    container_name: app_test
    depends_on:
      - redis
    command: sh -c "/app/wait && python -m pytest tests.py"
    ports:
    - "8000:8000"
    environment:
      - WAIT_HOSTS=redis:6379
      - REDIS_URL=redis://redis:6379/10
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
      - FLUSH_DB=1
